// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspproject.Data;

#nullable disable

namespace aspproject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250509093853_fixinggara")]
    partial class fixinggara
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspproject.Models.branche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeBranche")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("branche", (string)null);
                });

            modelBuilder.Entity("aspproject.Models.crma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeCRMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCRMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("crma", (string)null);
                });

            modelBuilder.Entity("aspproject.Models.detail_contrat", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<int>("assure_id")
                        .HasColumnType("int");

                    b.Property<double>("complement")
                        .HasColumnType("float");

                    b.Property<int>("crma_id")
                        .HasColumnType("int");

                    b.Property<string>("date_effet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_expiration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_police")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("exercice")
                        .HasColumnType("int");

                    b.Property<double>("montant_net_a_payer")
                        .HasColumnType("float");

                    b.Property<double>("numero_contrat")
                        .HasColumnType("float");

                    b.Property<string>("numero_police")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prime_nette")
                        .HasColumnType("float");

                    b.Property<double>("taxes")
                        .HasColumnType("float");

                    b.Property<double>("timbres")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("detail_contrat", (string)null);
                });

            modelBuilder.Entity("aspproject.Models.garantie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capital")
                        .HasColumnType("float");

                    b.Property<string>("CodeGarantie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_garantie");

                    b.Property<double>("ContratId")
                        .HasColumnType("float")
                        .HasColumnName("contrat_id");

                    b.Property<double>("ContratId1")
                        .HasColumnType("float");

                    b.Property<double>("Majoration")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrimeNette")
                        .HasColumnType("float")
                        .HasColumnName("prime_nette");

                    b.Property<double>("Reduction")
                        .HasColumnType("float");

                    b.Property<double>("detail_contratId")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContratId");

                    b.HasIndex("ContratId1");

                    b.ToTable("garantie", (string)null);
                });

            modelBuilder.Entity("aspproject.Models.synthese_contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrancheId")
                        .HasColumnType("int");

                    b.Property<decimal>("CapitalAssure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CotisationNette")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Creances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CrmaId")
                        .HasColumnType("int");

                    b.Property<int>("Exercice")
                        .HasColumnType("int");

                    b.Property<int>("NombreAvenants")
                        .HasColumnType("int");

                    b.Property<int>("NombreContrat")
                        .HasColumnType("int");

                    b.Property<decimal>("PrimeCommerciale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("synthese_contrat", (string)null);
                });

            modelBuilder.Entity("aspproject.Models.garantie", b =>
                {
                    b.HasOne("aspproject.Models.detail_contrat", null)
                        .WithMany("Garanties")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspproject.Models.detail_contrat", "Contrat")
                        .WithMany()
                        .HasForeignKey("ContratId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("aspproject.Models.detail_contrat", b =>
                {
                    b.Navigation("Garanties");
                });
#pragma warning restore 612, 618
        }
    }
}
